In [1]:
import os
import numpy as np
import cv2
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from keras.models import Model

In [12]:
# Define the paths to the data folders
train_path = "xray_dataset/xray_dataset/train_data"
test_path = "xray_dataset/xray_dataset/test_data"
#val_path = "xray_dataset/xray_dataset/validation_data"

In [13]:
# Define the classes and the number of classes
classes = ["COVID-19", "Normal","Pneumonia-Bacterial","Pneumonia-Viral"]
num_classes = len(classes)
# Define the image size and the batch size
img_size = 128
batch_size = 8

In [14]:
def load_data(path):
  images = []
  labels = []
  # Loop through each subfolder in the path
  for folder in os.listdir(path):
    class_index = classes.index(folder)
    for file in os.listdir(os.path.join(path, folder)):
      image = cv2.imread(os.path.join(path, folder, file))
      image = cv2.resize(image, (img_size, img_size))
      image = image / 255.0
      images.append(image)
      labels.append(class_index)
  images = np.array(images)
  labels = np.array(labels)
  return images, labels

In [15]:
train_images, train_labels = load_data(train_path)
test_images, test_labels = load_data(test_path)
#val_images, val_labels = load_data(val_path)
train_images.shape

(200, 128, 128, 3)

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(16, (3, 3), activation="relu", input_shape=(img_size, img_size, 3)),
  tf.keras.layers.Conv2D(16, (3, 3), activation="relu"),
  tf.keras.layers.Conv2D(8, (3, 3), activation="relu"),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(8, activation="relu"),
  tf.keras.layers.Dropout(0.2),
  # Add an output layer with num_classes units and softmax activation for multi-class classification
  tf.keras.layers.Dense(num_classes, activation="softmax")
])

c:\Users\faiza\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### model.compile is used to configure the learning process of the model. it has three parameters.
<b>1. Optimizer</b>
It determines how the model updates its weights during training. Optimizers minimize the loss function by adjusting weights in the network through backpropagation.<br>
Examples:<br>
'adam' (Adaptive Moment Estimation): Combines momentum and adaptive learning rates, widely used for CNNs.<br>
'sgd' (Stochastic Gradient Descent): Updates weights based on gradients and a learning rate.
'rmsprop' (Root Mean Square Propagation): Popular for recurrent neural networks but also applicable in CNNs.<br>
<b>2. Loss Function:</b><br>
Measures the difference between the predicted output and the actual target. The model tries to minimize this value.<br>
Examples:<br>
For binary classification: 'binary_crossentropy'<br>
For multi-class classification: 'categorical_crossentropy' (for one-hot encoded labels) or 'sparse_categorical_crossentropy' (for integer-encoded labels).
For regression tasks: 'mean_squared_error'<br>
<b>3. Metric:</b><br>
Specifies performance metrics to monitor during training and evaluation.<br>
Examples:<br>
<b>'accuracy':</b> Measures how often predictions match labels.<br>
<b>'precision':</b>, 'recall': Useful for imbalanced datasets.<br>
<b>'mae' (Mean Absolute Error):</b> Common in regression tasks.<br>


In [17]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [18]:
history = model.fit(train_images, train_labels, batch_size=batch_size, epochs=40)
#model.summary()

Epoch 1/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 70ms/step - accuracy: 0.2435 - loss: 1.4623
Epoch 2/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - accuracy: 0.2279 - loss: 1.3862
Epoch 3/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.2472 - loss: 1.3865
Epoch 4/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.2248 - loss: 1.3868
Epoch 5/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.1866 - loss: 1.3868
Epoch 6/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.2152 - loss: 1.3861
Epoch 7/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 85ms/step - accuracy: 0.2104 - loss: 1.3867
Epoch 8/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.2253 - loss: 1.3865
Epoch 9/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - accuracy: 0.2042 - loss: 1.3864
Epoch 10/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.2601 - loss: 1.3864
Epoch 11/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 70ms/step - accuracy: 0.2397 - loss: 1.3866
Epoch 12/40
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy:

In [19]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
history = model.fit(train_images, train_labels, batch_size=batch_size, epochs=4)
#model.summary()

Epoch 1/4
25/25 ━━━━━━━━━━━━━━━━━━━━ 8s 81ms/step - accuracy: 0.2154 - loss: 1.3865
Epoch 2/4
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 0.2165 - loss: 1.3866
Epoch 3/4
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - accuracy: 0.2542 - loss: 1.3864
Epoch 4/4
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 95ms/step - accuracy: 0.2316 - loss: 1.3864


In [21]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

In [23]:
history = model.fit(train_images, train_labels, batch_size=batch_size, epochs=10)
#model.summary()

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.1767 - loss: 1.3865
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.2183 - loss: 1.3865
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 66ms/step - accuracy: 0.2205 - loss: 1.3864
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.1910 - loss: 1.3865
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.2809 - loss: 1.3864
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 0.2092 - loss: 1.3865
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.2136 - loss: 1.3866
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.2160 - loss: 1.3864
Epoch 9/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.2323 - loss: 1.3864
Epoch 10/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.2226 - loss: 1.3864


In [24]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Get predictions
y_pred_probs = model.predict(test_images, batch_size=batch_size)  # Probabilities
y_pred = np.argmax(y_pred_probs, axis=1)  # Convert probabilities to class labels

# Compute confusion matrix
conf_matrix = confusion_matrix(test_labels, y_pred)

# Print confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# Optionally, print classification report
print("Classification Report:")
print(classification_report(test_labels, y_pred))


22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step
Confusion Matrix:
[[ 0  0  0 37]
 [ 0  0  0 50]
 [ 0  0  0 36]
 [ 0  0  0 50]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        37
           1       0.00      0.00      0.00        50
           2       0.00      0.00      0.00        36
           3       0.29      1.00      0.45        50

    accuracy                           0.29       173
   macro avg       0.07      0.25      0.11       173
weighted avg       0.08      0.29      0.13       173



c:\Users\faiza\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\faiza\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\faiza\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo