Numpy as a library

In [2]:
import numpy as np
arr_0 = [1,2,3,4,5,6,7,8,9]
arr_1 = [6,7,8,9,10,11,12,2]

arr_0 + arr_1
type(arr_0)

#arr_0 += 1 ----this won't work
#-------instead 
for i in range(len(arr_0)):
    arr_0[i] += 1
print(arr_0)

[2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
N_arr = np.array(arr_0)
print(type(N_arr))
print(N_arr.shape)

<class 'numpy.ndarray'>
(9,)


In [4]:
arr = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
arr.shape

(3, 3)

In [5]:
# Adding one to each element of the list
arr2 = arr + 1
print(arr2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
arr + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [7]:
arr * arr2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [33]:
print("Original array\n",arr2)
print("Slicing")
print(arr2[0][0:1])
arr2[::-1]


Original array
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Slicing
[2]


array([[ 8,  9, 10],
       [ 5,  6,  7],
       [ 2,  3,  4]])

In [9]:
#Multi-dimentional array with different datatypes
a = np.array(
    [
        [3,4,"Ola"], [4.5, True, 'A']
    ]
)
a

array([['3', '4', 'Ola'],
       ['4.5', 'True', 'A']], dtype='<U32')

In [10]:
#Appending an Element
arr = np.array([2,4,6])
print("Original Array : ",arr)
new_arr = np.append(arr, 8)
new_arr

Original Array :  [2 4 6]


array([2, 4, 6, 8])

In [11]:
#Adding an element at a specific index
arr_new = np.insert(arr,2,9)
arr_new
arr_new.size

4

In [12]:
print(arr_new.shape)
print(arr_new.ndim)


(4,)
1
